---
- name: "namedlock | install"
  hosts: all
  gather_facts: true

  tasks:
    - block:
        - ansible.builtin.import_role:
            name: namedlock
      become: "{{ install_scope | default('user') == 'system' }}"
